### ISSUE TITLE
about fully-connected layer shape

### ISSUE THREAD

**Issue by xingbow** [marcogdepinto/Emotion-Classification-Ravdess#1]
The network structure in the code is shown below:

While the fully-connected layer is (,10) and there are only 8 labels for emotion.
I wonder whether there is a mistake. And dense_1 and activation_3 should be (,8)

I found this issue while I run LivePredictions.py with new audio samples, when I get several 'null' results.

```
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
conv1d_1 (Conv1D)            (None, 40, 128)           768       
_________________________________________________________________
activation_1 (Activation)    (None, 40, 128)           0         
_________________________________________________________________
dropout_1 (Dropout)          (None, 40, 128)           0         
_________________________________________________________________
max_pooling1d_1 (MaxPooling1 (None, 5, 128)            0         
_________________________________________________________________
conv1d_2 (Conv1D)            (None, 5, 128)            82048     
_________________________________________________________________
activation_2 (Activation)    (None, 5, 128)            0         
_________________________________________________________________
dropout_2 (Dropout)          (None, 5, 128)            0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 640)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 10)                6410      
_________________________________________________________________
activation_3 (Activation)    (None, 10)                0         
=================================================================
Total params: 89,226
Trainable params: 89,226
Non-trainable params: 0
```

**Comment by marcogdepinto** [comment]
Update: after I read this issue (https://github.com/rstudio/keras/issues/465) I understood better the issue - it has been solved converting the labels from 0 to 7 because keras required the features to start from 0 (and not from 1 as in the previous version).
I am updating the model and the notebook.

**Comment by souravkumar123** [comment]
import time[

path = '/content/drive/My Drive/Ravdess/'
lst = []

start_time = time.time()

for subdir, dirs, files in os.walk(path):
  for file in files:
      try:
        #Load librosa array, obtain mfcss, store the file and the mcss information in a new array
        X, sample_rate = librosa.load(os.path.join(subdir,file), res_type='kaiser_fast')
        mfccs = np.mean(librosa.feature.mfcc(y=X, sr=sample_rate, n_mfcc=40).T,axis=0) 
        # The instruction below converts the labels (from 1 to 8) to a series from 0 to 7
        # This is because our predictor needs to start from 0 otherwise it will try to predict also 0.
        file = int(file[7:8]) - 1 
        arr = mfccs, file
        lst.append(arr)
      # If the file is not valid, skip it]([url]([url](url)))
      except ValueError:
        continue

print("--- Data loaded. Loading time: %s seconds ---" % (time.time() - start_time))


![Screenshot (10)](https://user-images.githubusercontent.com/62054832/78604829-072cb300-7878-11ea-8e70-5bccea960573.png)
