### ISSUE TITLE
VGGish as feature generator

### ISSUE THREAD

**Issue by SandeepBhutani** [marcogdepinto/Emotion-Classification-Ravdess#7]
Hi,
This is not an issue but a Question.  
Did you thing of or try applying VGGish features for training and prediction? Being a pretrained model, I think it may be more accurate. Whats your view on this?

**Comment by marcogdepinto** [comment]
Hi,
Could you please provide examples and documentation for this? I've never heard about VGgish features.
By the way this is a project I am not working on at the moment, if you want you can fork it and add a new branch with your experiments!

**Comment by marcogdepinto** [comment]
Hi,
Could you please provide examples and documentation for this? I've never heard about VGgish features.
By the way this is a project I am not working on at the moment, if you want you can fork it and add a new branch with your experiments!
